# Build image
# $ docker-compose build

# Ensure that your host can accept X forwarded connections
# $ xhost +local:aten_aten

# Run container
# $ docker-compose run aten

version: "2.4"
services:
  aten:
    build:
      context: "./"
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    container_name: aten-docker
    runtime: nvidia
    environment:
      - "DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "./:/aten"
