version: 2.1
jobs:
  build:
    docker:
      - image: dainack/aten:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: "Configure CMake"
          command: |
            cd build
            ./RunCMake.sh Release 75
      - run:
          name: "Run ninja"
          command: |
            cd build
            ninja -j 4
